---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-client-host
spec:
  containers:
  - name: netperf-client
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: leannet/k8s-netperf


