---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-server
  annotations:
     k8s.v1.cni.cncf.io/networks: '[{
      "name": "sriov-passthrough",
      "default-route": ["192.168.205.1"]
    }]'
spec:
  containers:
  - name: netperf-server
    command: ["usr/bin/netserver", "-D"]
    image: leannet/k8s-netperf
    resources:
      requests:
        intel.com/x550: 1
      limits:
        intel.com/x550: 1


